config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "pages/:permalink" => "pages#permalink", as: "permalink"
  # get 'home/index'
  # get 'games/index'
  # get 'games/show'
  # get 'publisher_companies/index'
  # get 'publisher_companies/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # to populate the games index with info go to games controler INDEX!
  root to: "home#index"

  resources :games, only: %i[index show] do
    collection do
      get "search"
    end
  end

  # resources :games, only: %i[index show]

  resources :publisher_companies, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :publisher_company
  has_many :game_genres
  has_many :games, through: :game_genres
  # validates :name, presence: true, uniqueness: true


  validates :name, :year, :north_america_sales, presence: true
  validates :name, uniqueness: true
  validates :year, numericality: { only_integer: true }
  validates :north_america_sales, numericality: true
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  #  need to map to game genre and to genres
  has_many :game_genres
  has_many :games, through: :game_genres
  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/publisher_company.rb
class PublisherCompany < ApplicationRecord
  has_many :games
  validates :name, presence: true, uniqueness: true

  def self.order_by_games
    self.select("publisher_companies.*")
        .select("COUNT(publisher_companies.id) as game_count")
        .left_joins(:games)
        .group("publisher_companies.id")
        .order("game_count DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages

  def cms_pages
    Page.all
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # this goes to views > games > index
  def index
    # @games = Game.includes(:publisher_company).all
    @games  = Game.paginate(page: params[:page], per_page: 5)
  end

  # this goes to views > games > show
  def show
    @game = Game.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @games = Game.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.includes(:publisher_company)
                 .order("north_america_sales DESC")
                 .limit(15)
    @publisher_companies = PublisherCompany.order_by_games.limit(20)
    #  PublisherCompany.select("publisher_companies.*")
    #  .select("COUNT(publisher_companies.id) as game_count")
    #  .left_joins(:games)
    #  .group("publisher_companies.id")
    #  .order("game_count DESC")
    #  .limit(20)
  end
end
# SELECT COUNT(*) AS game_count, publisher_companies.id, publisher_companies.name
# FROM publisher_companies
# JOIN games ON games.publisher_company_id = publisher_companies.id
# GROUP BY publisher_companies.id, publisher_companies.name
# ORDER BY game_count DESC;

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]
  http_basic_authenticate_with name: "haris", password: "Password01!", except: [:permalink]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to permalink_path(@page.permalink), notice: "Page created." }
        format.json { render :show, status: :created, location: permalink_path(@page.permalink) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to permalink_path(@page.permalink), notice: "Page updated." }
        format.json { render :show, status: :ok, location: permalink_path(@page.permalink) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/publisher_companies_controller.rb
class PublisherCompaniesController < ApplicationController
  def index
    # @publisher_companies = PublisherCompany.all
    @publisher_companies = PublisherCompany.order_by_games

    # PublisherCompany.select("publisher_companies.*")
    # .select("COUNT(publisher_companies.id) as game_count")
    # .left_joins(:games)
    # .group("publisher_companies.id")
    # .order("game_count DESC")
  end

  def show
    @publisher_company = PublisherCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publisher_companies_helper.rb
module PublisherCompaniesHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>Haris Top PS4 Games & Publishers</em></p>
  <ul class="mt-5">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Top Games", games_path %></li>
    <li><%= link_to "Top Publishers", publisher_companies_path %></li>

    <% cms_pages.each do |page|  %>
    <li><%= link_to page.title, permalink_path(page.permalink) %></li>

    <%end%>

  </ul>
</footer>

app/views/common/_my_game.html.erb
<hr>
<footer>
  <p><em>Haris' favorite games</em></p>
  <ul class="mt-5">

<li><%= text = "Check out my favourite game on youtube https://www.youtube.com/watch?v=dQw4w9WgXcQ"
html_text = text.gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %></li>
<li><%= link_to "About My Data", permalink_path('about_the_data') %></li>
<li><%= link_to "Contact", permalink_path('contact') %></li>

  </ul>
</footer>

app/views/games/_game.html.erb
<h2 class="title is-3">Game Info</h2>
<%#  input all details of the game here %>

<article class ="message is-danger">
  <div class="message-header">
      <% if show_link%>
        <p>Game Name: <%= link_to game.name, game%></p>
      <% else %>
       <p>Game Name: <%= game.name %></p>
      <%end%>
  </div>

  <%# <div class="message-body">
  </div> %>
</article>

<article class ="message is-primary">
  <div class="message-header">
  <p>Year Released: <%= game.year%> </p>
  </div>

  <%# <div class="message-body">
  </div> %>
</article>

<article class ="message is-success">
  <div class="message-header">
  <p>Sales in North America: <%= game.north_america_sales%> million </p>
  </div>

  <%# <div class="message-body">
  </div> %>
</article>

<article class ="message is-link">
  <div class="message-header">
  <p>Publisher: <%= link_to game.publisher_company.name, game.publisher_company %> </p>
  </div>

  <%# <div class="message-body">
  </div> %>
</article>

<hr>

app/views/games/index.html.erb
<%# <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
  <section class="section">
    <div class="container"> %>
    <%# ------------------------------------------- %>
      <h2 class="title">The Best PlayStation 4 Games Of All Time! Chg in views>games>index</h2>
       <figure class="image is-128x128 image is-inline-block" >
          <img src="https://assets1.ignimgs.com/2021/04/22/playstation-studios-1619090080230_160w.jpg?width=1280">
      </figure>

       <%= will_paginate @games %>
       <%= render partial: @games, locals: {show_link: true} %>
    <%# ------------------------------------------- %>
  <%# </section>
  </body>
</html> %>

app/views/games/search.html.erb
<p class="mb-5">
  Found <%= pluralize(@games.count, 'Game') %> when searching for: <%= params[:keywords] %>
</p>

<ul>
  <% @games.each do | game | %>
    <li><%= link_to game.name, game %> </li>
    <% end %>
</ul>

app/views/games/show.html.erb
<%# can use this for breadcrumb idea... right now used in application.html do display game name at top.. %>
<% content_for(:html_title) { @game.name} %>

<%# we can edit what this looks like in the _game.html.erb %>

<%= render partial: @game, locals: {show_link: false} %>

app/views/home/index.html.erb
<div class="columns">
  <div class="column box">
    <h2 class="title is-2"> Best Selling Games </h2>
    <ol class=ml-5>
    <%# loop through each game, make a link for that game, see the production company.. %>
      <% @games.each do | game |  %>
      <li>
       <button class="button is-link is-light"> <%= link_to game.name, game %></button>
        <em>(<%= game.publisher_company.name%>)</em>

        <progress class="progress is-danger" value="<%= game.north_america_sales %>" max=6.16>
          <%= game.north_america_sales%>
        </progress>

        </li>
      <% end  %>
    </ol>
  </div>


  <div class="column box">
  <h2 class="title is-2"> Most Games Published</h2>
      <ol class=ml-5>
    <%# loop through each game, make a link for that game, see the production company
        the partial knows to loop through it...  in views>publisher_companies>_publisher_companh %>
        <%= render @publisher_companies %>

    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<%#  What ever we want to be on everysingle page we put here %>

<!DOCTYPE html>
<html>
  <head>
  <%# append yield an dpass it a value that we declared... if there is a html_title for a game we will display that on the top tab if not Haris games project will display
  -	Changing something dynamically on screen %>
    <title><%= yield(:html_title) + "-" if content_for?(:html_title)%> Haris Games Project! </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>

  <body>
    <%# Headercan go here, all the pages will have this.... %>
    <section class="section box">
      <div class="buttons box">
        <h1 class="button is-dark"><%= link_to 'Games & Publishing Companies', root_path %></h1>
        <h1 class="button is-dark"><%= link_to "Games", games_path %></h1>
        <h1 class="button is-dark"><%= link_to "Publishers", publisher_companies_path %></h1>
        <%# Attempt Bread Crumb..  just delete <%#  %>
        <h3 class=" box"> Haris Games Project! > <%= yield(:html_title) + "-" if content_for?(:html_title)%></h3>
        </div>

     <% if controller_name == 'games' %>
          <%= form_with(url: search_games_path, method: :get, local: true) do %>
          <div class="field is-grouped mb-5">
            <div class="control is-expanded">
              <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For PS4 Games') %>
            </div>
            <div class="control">
              <%= submit_tag("Search", class: "button is-primary") %>
            </div>
          </div>
        <% end %>
      <% end %>

    <%= yield %>

    <% if controller_name == 'home' %>
      <%# <h1>What a Beautiful Page!</h1> %>
       <%= render partial: 'common/my_game'%>

    <% else %>
      <%= render partial: 'common/footer' %>
    <% end %>

    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title ,class: 'label' %>
    <%= form.text_field :title,class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :content,class: 'label' %>
    <%= form.text_area :content,class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.label :permalink,class: 'label' %>
    <%= form.text_field :permalink,class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%# <h1>Editing Page</h1> %>
<h2 class = "title is-4">Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class = "title is-4">Pages</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page, class: 'button is-warning' %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-info' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-danger' %>

app/views/pages/new.html.erb
<%# <h1>New Page</h1> %>
<h2 class = "title is-4">New Page</h1>


<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/publisher_companies/_publisher_company.html.erb
 <li>
       <button class="button is-link is-light"> <%= link_to publisher_company.name, publisher_company %></button>
        <em>(<%= pluralize publisher_company.game_count, "Best Game"%> Best Games   find in views>home>index)</em>

        <progress class="progress is-danger" value="<%= publisher_company.game_count %>" max=27>
          <%= publisher_company.game_count%>
        </progress>

 </li>

app/views/publisher_companies/index.html.erb
<%# <p>Find me in app/views/publisher_companies/index.html.erb</p> %>

 <h2 class="title is-2 box"> The Top Producing Publishing Companies In The Video Game Industry</h2>
      <ol class=ml-5>
    <%# loop through each game, make a link for that game, see the production company.. %>
      <%= render @publisher_companies %>
    </ol>

app/views/publisher_companies/show.html.erb
<p>Find me in app/views/publisher_companies/show.html.erb</p>

<h2 class="title is-2"><%= @publisher_company.name%></h2>

<p class='mb-5 box'>
  <%= @publisher_company.name%> created <%= @publisher_company.games.count %> of the top games sold this year
</p>

<h3 class='title is-3 box'> Games made by <%= @publisher_company.name%></h3>
<%# <div class="bulma-clearfix-mixin">
  <img height="80" width="80" style="float: left;" src="https://source.unsplash.com/La2kOu2dmH4/160x160">
  <p>This is a short image description.</p>
</div> %>

  <ul>

  <%# we can also use render partial for publisher companies here for a different look %>
    <% @publisher_company.games.each do |game|%>
      <li><%= link_to game.name, game %> has sold <%= game.north_america_sales %> million games! </li>
    <% end %>
  </ul>